# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


users = User.create[{email: "k@k", password: '12345678'},{email: "j@j", password: '12345678'}]

posts = Posts.create[{title: "The Difference between React and Ractive", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus lacinia pharetra. Fusce eu rhoncus felis. Curabitur interdum nec erat at laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi non magna quis ex posuere varius id et dolor. Maecenas augue metus, pulvinar sit amet lobortis non, ultrices eget eros. Suspendisse nisi velit, hendrerit dapibus arcu ut, feugiat laoreet eros. Integer eget enim rutrum, semper ante at, ornare eros.
                  Etiam a nibh ipsum. Vestibulum sapien mauris, pharetra quis porttitor nec, facilisis sit amet ligula. Integer tincidunt pulvinar viverra. Nam non nunc pulvinar, consectetur nisi in, pretium dolor. Praesent vestibulum purus non metus imperdiet porta. Fusce id finibus massa, at tempor purus. Nam iaculis tristique ipsum scelerisque imperdiet. Praesent eget magna sodales, egestas est eu, eleifend arcu. Proin iaculis pellentesque ipsum vel egestas. Nulla finibus ipsum ut tortor bibendum tristique. In porttitor tincidunt odio vitae auctor. Donec eu sagittis dui, non aliquam velit. Praesent sed ultrices ligula, in suscipit dui. Nulla facilisi. Cras dignissim augue a neque ornare aliquam.
                  Nam quam ligula, sollicitudin in sem vitae, consequat semper sem. Sed facilisis cursus finibus. Aliquam
                  molestie tellus eu dui aliquet, eu posuere lorem finibus. Aliquam consectetur laoreet magna at eleifend. Integer mattis, lacus non vulputate condimentum, nisi dui pellentesque metus, at malesuada eros nisi quis felis. Quisque lobortis commodo lectus, auctor fermentum nunc vulputate quis. Ut lectus risus, vulputate nec purus eu, gravida consequat augue. Nam vulputate lacus in ipsum iaculis, vel vehicula purus sodales. Sed urna nisi, semper eu condimentum vel, sodales eget lectus. Mauris imperdiet arcu lectus, vel dignissim nunc feugiat dignissim. Nullam interdum ipsum ipsum, nec molestie velit porta eget."},
        {title: "The Difference between Anjular and Ember and Ractive", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus lacinia pharetra. Fusce eu rhoncus felis. Curabitur interdum nec erat at laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi non magna quis ex posuere varius id et dolor. Maecenas augue metus, pulvinar sit amet lobortis non, ultrices eget eros. Suspendisse nisi velit, hendrerit dapibus arcu ut, feugiat laoreet eros. Integer eget enim rutrum, semper ante at, ornare eros. Etiam a nibh ipsum.
                Vestibulum sapien mauris, pharetra quis porttitor nec, facilisis sit amet ligula. Integer tincidunt pulvinar viverra. Nam non nunc pulvinar, consectetur nisi in, pretium dolor. Praesent vestibulum purus non metus imperdiet porta. Fusce id finibus massa, at tempor purus. Nam iaculis tristique ipsum scelerisque imperdiet. Praesent eget magna sodales, egestas est eu, eleifend arcu. Proin iaculis pellentesque ipsum vel egestas. Nulla finibus ipsum ut tortor bibendum tristique. In porttitor tincidunt odio vitae auctor. Donec eu sagittis dui, non aliquam velit. Praesent sed ultrices ligula, in suscipit dui. Nulla facilisi. Cras dignissim augue a neque ornare aliquam.
                Nam quam ligula, sollicitudin in sem vitae, consequat semper sem. Sed facilisis cursus finibus. Aliquam molestie tellus eu dui aliquet, eu posuere lorem finibus. Aliquam consectetur laoreet magna at eleifend. Integer mattis, lacus non vulputate condimentum, nisi dui pellentesque metus, at malesuada eros nisi quis felis. Quisque lobortis commodo lectus, auctor fermentum nunc vulputate quis. Ut lectus risus, vulputate nec purus eu, gravida consequat augue. Nam vulputate lacus in ipsum iaculis, vel vehicula purus sodales. Sed urna nisi, semper eu condimentum vel, sodales eget lectus. Mauris imperdiet arcu lectus, vel dignissim nunc feugiat dignissim. Nullam interdum ipsum ipsum, nec molestie velit porta eget."},

        {title: "The Difference between Anjular and Ember and Ractive", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus lacinia pharetra. Fusce eu rhoncus felis. Curabitur interdum nec erat at laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi non magna quis ex posuere varius id et dolor. Maecenas augue metus, pulvinar sit amet lobortis non, ultrices eget eros. Suspendisse nisi velit, hendrerit dapibus arcu ut, feugiat laoreet eros. Integer eget enim rutrum, semper ante at, ornare eros. Etiam a nibh ipsum.
                Vestibulum sapien mauris, pharetra quis porttitor nec, facilisis sit amet ligula. Integer tincidunt pulvinar viverra. Nam non nunc pulvinar, consectetur nisi in, pretium dolor. Praesent vestibulum purus non metus imperdiet porta. Fusce id finibus massa, at tempor purus. Nam iaculis tristique ipsum scelerisque imperdiet. Praesent eget magna sodales, egestas est eu, eleifend arcu. Proin iaculis pellentesque ipsum vel egestas. Nulla finibus ipsum ut tortor bibendum tristique. In porttitor tincidunt odio vitae auctor. Donec eu sagittis dui, non aliquam velit. Praesent sed ultrices ligula, in suscipit dui. Nulla facilisi. Cras dignissim augue a neque ornare aliquam.
                Nam quam ligula, sollicitudin in sem vitae, consequat semper sem. Sed facilisis cursus finibus. Aliquam molestie tellus eu dui aliquet, eu posuere lorem finibus. Aliquam consectetur laoreet magna at eleifend. Integer mattis, lacus non vulputate condimentum, nisi dui pellentesque metus, at malesuada eros nisi quis felis. Quisque lobortis commodo lectus, auctor fermentum nunc vulputate quis. Ut lectus risus, vulputate nec purus eu, gravida consequat augue. Nam vulputate lacus in ipsum iaculis, vel vehicula purus sodales. Sed urna nisi, semper eu condimentum vel, sodales eget lectus. Mauris imperdiet arcu lectus, vel dignissim nunc feugiat dignissim. Nullam interdum ipsum ipsum, nec molestie velit porta eget."}]
